version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - NODE_ENV=dev npm ci
      - (cd client && npm ci)
  pre_build:
    on-failure: ABORT # or CONTINUE
    commands:
      - npm run test:format
      - npm run test:license
      - cd client
      # - npm run test:audit
      - npm run test:lint
      - npm run test:types
      # # cypress tests - its cheaper to run them in github actions

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
